In [24]:
import numpy as np
import pandas as pd

In [25]:
patients = pd.read_csv('mortality.csv')

In [26]:
patients.dtypes

group                         int64
ID                            int64
outcome                     float64
age                           int64
gendera                       int64
BMI                         float64
hypertensive                  int64
atrialfibrillation            int64
CHD with no MI                int64
diabetes                      int64
deficiencyanemias             int64
depression                    int64
Hyperlipemia                  int64
Renal failure                 int64
COPD                          int64
heart rate                  float64
Systolic blood pressure     float64
Diastolic blood pressure    float64
Respiratory rate            float64
temperature                 float64
SP O2                       float64
Urine output                float64
hematocrit                  float64
RBC                         float64
MCH                         float64
MCHC                        float64
MCV                         float64
RDW                         float64
Leucocyte                   float64
Platelets                   float64
Neutrophils                 float64
Basophils                   float64
Lymphocyte                  float64
PT                          float64
INR                         float64
NT-proBNP                   float64
Creatine kinase             float64
Creatinine                  float64
Urea nitrogen               float64
glucose                     float64
Blood potassium             float64
Blood sodium                float64
Blood calcium               float64
Chloride                    float64
Anion gap                   float64
Magnesium ion               float64
PH                          float64
Bicarbonate                 float64
Lactic acid                 float64
PCO2                        float64
EF                            int64
dtype: object

In [27]:
patients = patients.astype('float64')
patients.dtypes

group                       float64
ID                          float64
outcome                     float64
age                         float64
gendera                     float64
BMI                         float64
hypertensive                float64
atrialfibrillation          float64
CHD with no MI              float64
diabetes                    float64
deficiencyanemias           float64
depression                  float64
Hyperlipemia                float64
Renal failure               float64
COPD                        float64
heart rate                  float64
Systolic blood pressure     float64
Diastolic blood pressure    float64
Respiratory rate            float64
temperature                 float64
SP O2                       float64
Urine output                float64
hematocrit                  float64
RBC                         float64
MCH                         float64
MCHC                        float64
MCV                         float64
RDW                         float64
Leucocyte                   float64
Platelets                   float64
Neutrophils                 float64
Basophils                   float64
Lymphocyte                  float64
PT                          float64
INR                         float64
NT-proBNP                   float64
Creatine kinase             float64
Creatinine                  float64
Urea nitrogen               float64
glucose                     float64
Blood potassium             float64
Blood sodium                float64
Blood calcium               float64
Chloride                    float64
Anion gap                   float64
Magnesium ion               float64
PH                          float64
Bicarbonate                 float64
Lactic acid                 float64
PCO2                        float64
EF                          float64
dtype: object

In [28]:
patients.dropna(inplace = True)
patients

,group,ID,outcome,age,gendera,BMI,hypertensive,atrialfibrillation,CHD with no MI,diabetes,...,Blood sodium,Blood calcium,Chloride,Anion gap,Magnesium ion,PH,Bicarbonate,Lactic acid,PCO2,EF
0,1.0,125047.0,0.0,72.0,1.0,37.588179,0.0,0.0,0.0,1.0,...,138.750000,7.463636,109.166667,13.166667,2.618182,7.230000,21.166667,0.500,40.000000,55.0
2,1.0,109787.0,0.0,83.0,2.0,26.572634,0.0,0.0,0.0,0.0,...,140.714286,8.266667,105.857143,10.000000,2.157143,7.268000,30.571429,0.500,71.500000,35.0
3,1.0,130587.0,0.0,43.0,2.0,83.264629,0.0,0.0,0.0,0.0,...,138.500000,9.476923,92.071429,12.357143,1.942857,7.370000,38.571429,0.600,75.000000,55.0
5,1.0,154653.0,0.0,76.0,1.0,24.262293,1.0,1.0,0.0,0.0,...,136.250000,8.466667,96.750000,13.125000,1.771429,7.310000,30.500000,0.600,65.500000,35.0
6,1.0,194420.0,0.0,72.0,1.0,39.667426,1.0,0.0,0.0,0.0,...,144.133333,8.775000,106.666667,15.200000,1.875000,7.169231,26.800000,0.625,69.769231,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1088,2.0,127201.0,0.0,83.0,1.0,20.347657,1.0,1.0,0.0,0.0,...,137.800000,7.925000,102.400000,16.600000,2.250000,7.273333,23.000000,3.550,48.333333,55.0
1090,2.0,149303.0,0.0,37.0,1.0,26.638051,0.0,0.0,0.0,0.0,...,135.666667,8.400000,100.333333,13.333333,2.050000,7.370000,26.333333,3.775,29.000000,20.0
1091,2.0,130745.0,0.0,61.0,1.0,29.836962,1.0,0.0,0.0,1.0,...,135.444444,8.571429,99.444444,15.888889,1.900000,7.368125,24.333333,4.150,43.000000,20.0
1092,2.0,177737.0,0.0,71.0,2.0,32.804298,1.0,0.0,0.0,1.0,...,141.823529,8.500000,101.470588,12.066667,2.005882,7.385806,32.933333,4.160,42.870968,55.0
1094,2.0,122715.0,0.0,37.0,1.0,26.255155,0.0,0.0,0.0,0.0,...,126.230769,8.000000,92.923077,16.083333,2.141667,7.430000,21.666667,4.200,21.000000,15.0

In [29]:
patients.describe()

,group,ID,outcome,age,gendera,BMI,hypertensive,atrialfibrillation,CHD with no MI,diabetes,...,Blood sodium,Blood calcium,Chloride,Anion gap,Magnesium ion,PH,Bicarbonate,Lactic acid,PCO2,EF
count,428.000000,428.000000,428.000000,428.000000,428.000000,428.000000,428.000000,428.000000,428.000000,428.000000,...,428.000000,428.000000,428.000000,428.000000,428.000000,428.000000,428.000000,428.000000,428.000000,428.000000
mean,1.296729,149915.925234,0.151869,72.514019,1.516355,30.858403,0.703271,0.422897,0.067757,0.457944,...,139.326967,8.448076,102.614122,14.116525,2.135186,7.374790,26.820936,1.900347,45.381160,48.154206
std,0.457351,29344.275672,0.359314,13.424689,0.500317,9.630081,0.457351,0.494598,0.251623,0.498811,...,3.926662,0.563461,5.200159,2.644287,0.242133,0.065736,5.621605,0.997925,13.019605,13.043058
min,1.000000,100571.000000,0.000000,35.000000,1.000000,13.673625,0.000000,0.000000,0.000000,0.000000,...,121.045455,6.700000,85.642857,7.777778,1.414286,7.158333,12.857143,0.500000,19.500000,15.000000
25%,1.000000,125324.500000,0.000000,63.000000,1.000000,24.431441,0.000000,0.000000,0.000000,0.000000,...,137.000000,8.089722,99.305769,12.250000,1.978750,7.330000,23.000000,1.200000,36.958333,40.000000
50%,1.000000,150454.000000,0.000000,74.000000,2.000000,28.429763,1.000000,0.000000,0.000000,0.000000,...,139.727273,8.440833,102.636364,13.891176,2.100000,7.375778,26.186813,1.660000,42.450000,55.000000
75%,2.000000,175120.500000,0.000000,84.000000,2.000000,34.460033,1.000000,1.000000,0.000000,1.000000,...,142.000000,8.800000,105.865079,15.673077,2.243506,7.425000,29.750000,2.300000,50.520833,55.000000
max,2.000000,199925.000000,1.000000,99.000000,2.000000,83.264629,1.000000,1.000000,1.000000,1.000000,...,149.133333,10.950000,117.315789,25.272727,4.072727,7.560000,47.666667,6.725000,98.600000,75.000000

In [30]:
np.isnan(patients)

,group,ID,outcome,age,gendera,BMI,hypertensive,atrialfibrillation,CHD with no MI,diabetes,...,Blood sodium,Blood calcium,Chloride,Anion gap,Magnesium ion,PH,Bicarbonate,Lactic acid,PCO2,EF
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1088,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1090,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1091,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1092,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1094,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [31]:
xcolumns = ['age', 'gendera', 'BMI', 'hypertensive',
       'atrialfibrillation', 'CHD with no MI', 'diabetes', 'deficiencyanemias',
       'depression', 'Hyperlipemia', 'Renal failure', 'COPD', 'heart rate',
       'Systolic blood pressure', 'Diastolic blood pressure',
       'Respiratory rate', 'temperature', 'SP O2', 'Urine output',
       'hematocrit', 'RBC', 'MCH', 'MCHC', 'MCV', 'RDW', 'Leucocyte',
       'Platelets', 'Neutrophils', 'Basophils', 'Lymphocyte', 'PT', 'INR',
       'NT-proBNP', 'Creatine kinase', 'Creatinine', 'Urea nitrogen',
       'glucose', 'Blood potassium', 'Blood sodium', 'Blood calcium',
       'Chloride', 'Anion gap', 'Magnesium ion', 'PH', 'Bicarbonate',
       'Lactic acid', 'PCO2', 'EF']
df = patients[xcolumns]
#df.head()
yvalues = patients['outcome']

In [32]:
exist = patients.index[patients.ID == 182755]
if exist.size > 0:
    print(exist)
    print(df.loc[exist,:].values.tolist())
else:
    print("Patient ID does not exist")

Int64Index([21], dtype='int64')
[[78.0, 2.0, 37.85143414, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 76.38461538, 95.44444444, 60.25925926, 21.75, 36.12037037, 94.38461538, 1766.0, 34.1625, 4.2175, 26.0125, 32.125, 81.0, 19.0625, 4.8375, 172.25, 70.9, 0.5, 17.9, 14.2, 1.2, 24440.0, 24.0, 1.3, 32.72727273, 88.0, 3.481818182, 142.8181818, 8.32, 107.4545455, 12.54545455, 2.01, 7.333333333, 26.36363636, 0.75, 52.0, 55.0]]

In [33]:

yvalues.value_counts()

0.0    363
1.0     65
Name: outcome, dtype: int64

In [34]:
#pip install xgboost

In [40]:
# Modeling
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost.sklearn import XGBClassifier
from sklearn.ensemble import GradientBoostingClassifier

from sklearn import metrics

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

In [41]:
X = df
y = yvalues
#X.shape
#y.shape
from sklearn.impute import SimpleImputer
my_imputer = SimpleImputer()
X = my_imputer.fit_transform(X)

In [46]:
from sklearn.model_selection import train_test_split
#split data into training and testing
x_train, x_test, y_train, y_test = train_test_split(X,y, random_state=42)#0.33% of data is reserved for testing, algorithm will never see it.
print(x_train,y_train)
def find_best_model(X, y):
    # Logistic Regression
    logreg = LogisticRegression(max_iter = 500)
    logreg.fit(X, y)
    logreg_acc = round(logreg.score(X, y) * 100, 2)
    
    # Decision Tree
    decision_tree = DecisionTreeClassifier()
    decision_tree.fit(X, y)
    decision_tree_acc = round(decision_tree.score(X, y) * 100, 2)
    
    # Random Forest
    random_forest = RandomForestClassifier()
    random_forest.fit(X, y)
    random_forest_acc = round(random_forest.score(X, y) * 100, 2)
    
    # XGBoost
    xgb = XGBClassifier()
    xgb.fit(X, y)
    xgb_acc = round(xgb.score(X, y) * 100, 2)
    
    # GBM
    gbm = GradientBoostingClassifier()
    gbm.fit(X, y)
    gbm_acc = round(gbm.score(X, y) * 100, 2)
    
   
    model_df = pd.DataFrame({'Model': ['Logistic Regression', 'Decision Tree', 'Random Forest', 'XGBoost', 'GBM'],
                       'Score': [logreg_acc, decision_tree_acc, random_forest_acc, xgb_acc, gbm_acc]})
    print(model_df.sort_values('Score', ascending = False).reset_index(drop = True))

find_best_model(x_train,y_train)

[[85.          2.         43.06460226 ...  0.8        62.5
  55.        ]
 [76.          1.         24.26229342 ...  0.6        65.5
  35.        ]
 [64.          2.         36.53770283 ...  0.86       62.5
  55.        ]
 ...
 [86.          2.         27.62313388 ...  3.325      43.5
  35.        ]
 [76.          2.         43.26621556 ...  1.475      42.5
  55.        ]
 [72.          1.         35.1141349  ...  1.33333333 36.14285714
  35.        ]] 834    0.0
5      0.0
46     0.0
885    0.0
136    0.0
      ...
154    0.0
237    0.0
618    1.0
927    0.0
229    0.0
Name: outcome, Length: 321, dtype: float64

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

                 Model   Score
0        Decision Tree  100.00
1        Random Forest  100.00
2              XGBoost  100.00
3                  GBM  100.00
4  Logistic Regression   90.03

In [47]:
log_reg = LogisticRegression()
log_reg.fit(x_train, y_train)

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [48]:
samples = [78.0, 2.0, 37.85143414, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 76.38461538, 95.44444444, 60.25925926, 21.75, 36.12037037, 94.38461538, 1766.0, 34.1625, 4.2175, 26.0125, 32.125, 81.0, 19.0625, 4.8375, 172.25, 70.9, 0.5, 17.9, 14.2, 1.2, 24440.0, 24.0, 1.3, 32.72727273, 88.0, 3.481818182, 142.8181818, 8.32, 107.4545455, 12.54545455, 2.01, 7.333333333, 26.36363636, 0.75, 52.0, 55.0]
samples = pd.Series(data=samples)
sample_X = pd.Series(data=[])
sample_X = sample_X.append(samples)
sample_X = np.array(sample_X).reshape(1,-1)


answer = log_reg.predict_proba(sample_X)
treatment = log_reg.predict(sample_X)
print(treatment)
if treatment == 0:
    print(f"With {answer*100}% accuracy, you are LIKELY to leave hospital ALIVE.")
else:
    print(f"With {100-answer*100}% accuracy, you are UNLIKELY to leave hospital ALIVE.")

[0.]
With [[92.61625261  7.38374739]]% accuracy, you are LIKELY to leave hospital ALIVE.

C:\Users\DELL\AppData\Local\Temp\ipykernel_20744\179986739.py:3: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  sample_X = pd.Series(data=[])
C:\Users\DELL\AppData\Local\Temp\ipykernel_20744\179986739.py:4: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sample_X = sample_X.append(samples)